- name: "filebeat uninstall"
  hosts: "{{hosts}}"
  become: yes
  tasks:
  - name: stopped filebeat service
    service:
      name={{id}}
      enabled=no
      state=stopped
      ignore_errors: True
  - name: stopped filebeat service
    service:
      name=filebeat
      enabled=no
      state=stopped
      ignore_errors: True
  - name: reload all service
    shell: systemctl daemon-reload
    ignore_errors: True
  - name: remove filebeat id service file
    shell: rm -f /etc/systemd/system/*_filebeat_*.service
    when: ansible_distribution_major_version == "7"
  - name: remove filebeat service file
    shell: rm -f /etc/systemd/system/filebeat.service
    when: ansible_distribution_major_version == "7"
  - name: remove filebeat agent
    shell: rm -f /usr/sbin/filebeat/filebeat-{{version}}
  - name: remove /root/Downloads/{{id}}.yml
    shell: rm -f /root/Downloads/{{id}}.yml
  - name: remove /etc/filebeat/filebeat.yml
    shell: rm -f /etc/filebeat/filebeat.yml
