- name: "filebeat uninstall"
  hosts: "{{hosts}}"
  become: yes
  tasks:
  - name: stopped filebeat service
    service:
      name={{id}}
      enabled=no
      state=stopped
  - name: reload all service
    shell: systemctl daemon-reload
    ignore_errors: True
  - name: remove filebeat service file 
    shell: rm -f /etc/systemd/system/{{id}}.service
    when: ansible_distribution_major_version == "7"
  - name: remove filebeat agent
    shell: rm -f /usr/sbin/filebeat/{{project}}/filebeat-{{version}}
  - name: remove filebeat yml
    shell: rm -f /root/Downloads/{{id}}.yml
